name: qbittorrent-arm
services:
  qbittorrent-arm:
    environment:
      PGID: $PGID
      PUID: $PUID
      TZ: $TZ
      UMASK: "002"
    image: hotio/qbittorrent:release-2505739-334-linux-arm-v7
    deploy:
      resources:
        reservations:
          memory: "256M"
    network_mode: bridge
    ports:
      - target: 8080
        published: "8181"
        protocol: tcp
    restart: unless-stopped
    volumes:
      - type: bind
        source: /DATA/AppData/qbittorrent-arm/config
        target: /config
      - type: bind
        source: /DATA
        target: /DATA
    x-casaos:
      envs:
        - container: TZ
          description:
            en_us: TimeZone
            zh_cn: 时区
        - container: PUID
          description:
            en_us: Run qBittorrent as specified uid.
            zh_cn: 以指定的 uid 运行 qBittorrent。
        - container: PGID
          description:
            en_us: Run qBittorrent as specified gid.
            zh_cn: 以指定的 gid 运行 qBittorrent。
        - container: UMASK
          description:
            en_us: Run qBittorrent as specified UMASK.
            zh_cn: 以指定的 UMASK 运行 qBittorrent。
      ports:
        - container: "8080"
          description:
            en_us: WebUI HTTP Port
            zh_cn: WebUI HTTP 端口

      volumes:
        - container: /config
          description:
            en_us: qBittorrent config directory.
            zh_cn: qBittorrent 配置目录。
        - container: /DATA
          description:
            en_us: qBittorrent Accessible directory.
            zh_cn: qBittorrent 可访问目录。
    container_name: qbittorrent-arm
x-casaos:
  architectures:
    - arm
  main: qbittorrent-arm
  author: CasaOS Team
  category: Downloader
  description:
    en_us: The qBittorrent project aims to provide an open-source software alternative to µTorrent.
    zh_cn: qBittorrent 项目旨在提供一个开源的 µTorrent 替代品。
    ar_sa: يهدف مشروع qBittorrent إلى توفير بديل مفتوح المصدر لـ µTorrent.
    de_de: Das qBittorrent-Projekt zielt darauf ab, eine Open-Source-Software-Alternative zu µTorrent zu bieten.
    es_es: El objetivo del proyecto qBittorrent es proporcionar una alternativa de software de código abierto a µTorrent.
    fr_fr: Le projet qBittorrent vise à fournir une alternative open source à µTorrent.
    hu_hu: A qBittorrent projekt célja, hogy nyílt forráskódú szoftver alternatívát nyújtson a µTorrent számára.
    it_it: Il progetto qBittorrent mira a fornire un'alternativa open source a µTorrent.
    ru_ru: Проект qBittorrent стремится предоставить альтернативу с открытым исходным кодом для µTorrent.
    pl_pl: Projekt qBittorrent ma na celu zapewnienie otwartoźródłowej alternatywy dla µTorrent.
    pt_br: O objetivo do projeto qBittorrent é fornecer uma alternativa de software de código aberto ao µTorrent.
    sv_se: qBittorrent-projektets mål är att erbjuda en öppen källkodsalternativ till µTorrent.
    uk_ua: Проект qBittorrent має на меті надати альтернативу з відкритим вихідним кодом для µTorrent.
  developer: qBittorrent
  icon: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/qBittorrent/icon.png
  screenshot_link:
    - https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/qBittorrent/screenshot-1.jpg
    - https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/qBittorrent/screenshot-2.jpg
  tagline:
    en_us: Free BitTorrent downloader
    zh_cn: 免费的 BitTorrent 下载器
    ar_sa: مُنزِّل BitTorrent مجاني
    de_de: Kostenloser BitTorrent-Downloader
    es_es: Descargador de BitTorrent gratuito
    fr_fr: Téléchargeur BitTorrent gratuit
    hu_hu: Ingyenes BitTorrent letöltő
    it_it: Downloader BitTorrent gratuito
    ru_ru: Бесплатный загрузчик BitTorrent
    pl_pl: Darmowy downloader BitTorrent
    pt_br: Downloader BitTorrent gratuito
    sv_se: Gratis BitTorrent-downladdare
    uk_ua: Безкоштовний завантажувач BitTorrent
  thumbnail: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/qBittorrent/thumbnail.jpg
  tips:
    before_install:
      en_us: |
        Default Account

        | Username | Password |
        |----------|----------|
        | `admin`    | `adminadmin` |

        Default Accessible Path in qBittorrent

        | Name | Value |
        | ---- | ----- |
        | DATA Path | `/DATA` |
        | Downloads Path | `/DATA/Downloads` |
        | Media Path | `/DATA/Media` |

        The paths of other DATA subdirectories in CasaOS are also similar.
        Please make sure you use the correct path when using qBittorrent.
      zh_cn: |
        默认账号

        | 用户名 | 密码 |
        |----------|----------|
        | `admin`    | `adminadmin` |

        qBittorrent 默认可访问路径

        | 名称 | 值 |
        | ---- | ----- |
        | DATA 路径 | `/DATA` |
        | 下载路径 | `/DATA/Downloads` |
        | 媒体路径 | `/DATA/Media` |

        CasaOS 其他 DATA 子目录的路径也类似。
        请确保在使用 qBittorrent 时使用正确的路径。

  title:
    en_us: qBittorrent
  index: /
  port_map: "8181"
