name: smartstrm
services:
  smartstrm:
    image: cp0204/smartstrm:latest
    container_name: smartstrm
    restart: unless-stopped
    network_mode: host
    volumes:
      - /DATA/AppData/smartstrm/config:/app/config # æŒ‚è½½é…ç½®ç›®å½•
      - /DATA/AppData/smartstrm/logs:/app/logs # æŒ‚è½½æ—¥å¿—ç›®å½•ï¼Œå¯é€‰
      - /DATA/AppData/smartstrm/strm:/strm # æŒ‚è½½ STRM ç”Ÿæˆç›®å½•
    environment:
      - PORT=8024 # ç®¡ç†ç«¯å£ï¼Œå¯é€‰
      - ADMIN_USERNAME=admin # ç®¡ç†ç”¨æˆ·å
      - ADMIN_PASSWORD=admin123 # ç®¡ç†ç”¨æˆ·å¯†ç 
      - LICENSE= # è®¸å¯è¯å­—ç¬¦ä¸²ï¼ˆå¦‚æœ‰ï¼‰
    deploy:
      resources:
        reservations:
          memory: 128M

x-casaos:
  architectures:
    - amd64
    - arm64
  main: smartstrm
  store_app_id: smartstrm
  author: Cp0204
  category: Media
  description:
    en_us: A media library STRM file generation tool. It works elegantly with Emby, supports 302 direct link playback, and supports synchronous deletion of remote files.
    zh_cn: ä¸€ä¸ªåª’ä½“åº“ STRM æ–‡ä»¶ç”Ÿæˆå·¥å…·ã€‚å’Œ Emby ä¼˜é›…é…åˆï¼Œæ”¯æŒ 302 ç›´é“¾æ’­æ”¾ï¼Œæ”¯æŒåŒæ­¥åˆ é™¤è¿œç«¯æ–‡ä»¶ã€‚æ­£å¦‚å…¶åï¼Œé…åˆ quark-auto-save/CloudSaver, OpenList, Emby åŠ›æ±‚å³å­˜å³çœ‹ã€‚ğŸ¥³
  developer: Cp0204
  icon: https://cdn.jsdelivr.net/gh/Cp0204/CasaOS-AppStore-Play@main/Apps/smartstrm/icon.png
  screenshot_link:
    - https://cdn.jsdelivr.net/gh/Cp0204/CasaOS-AppStore-Play@main/Apps/smartstrm/screenshot-1.png
  tagline:
    en_us: A media library STRM file generation tool
    zh_cn: åª’ä½“åº“ STRM æ–‡ä»¶ç”Ÿæˆå·¥å…·
  tips:
    before_install:
      en_us: Default username `admin` , password `admin123`
      zh_cn: é»˜è®¤ç”¨æˆ·å `admin`ï¼Œå¯†ç  `admin123`
  title:
    en_us: SmartStrm
  index: /
  port_map: "8024"
