version: "3.8"
name: casamod
services:
  casamod:
    #build: .
    container_name: casamod
    image: cp0204/casamod:latest
    volumes:
      - /DATA/AppData/casamod:/DATA/AppData/casamod
      - /var/lib/casaos/www:/var/lib/casaos/www
    network_mode: bridge
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          memory: 8M

x-casaos:
  architectures:
    - amd64
    - arm
    - arm64
  main: casamod
  store_app_id: casamod
  category: Developer
  author: Cp0204
  developer: Cp0204
  icon: https://cdn.jsdelivr.net/gh/Cp0204/CasaOS-AppStore-Play@main/Apps/casamod/icon.png
  screenshot_link:
    - https://cdn.jsdelivr.net/gh/Cp0204/CasaOS-AppStore-Play@main/Apps/casamod/screenshot-1.png
    - https://cdn.jsdelivr.net/gh/Cp0204/CasaOS-AppStore-Play@main/Apps/casamod/screenshot-2.png
    - https://cdn.jsdelivr.net/gh/Cp0204/CasaOS-AppStore-Play@main/Apps/casamod/screenshot-3.png
  # thumbnail: https://cdn.jsdelivr.net/gh/Cp0204/CasaOS-AppStore-Play@main/Apps/casamod/thumbnail.png
  description:
    en_us: Add MODs like a game, and elegantly make some fancy modifications to the CasaOS frontend. Examples include mouse effects, animated wallpapers, modified themes, and more.
    zh_cn: åƒæ¸¸æˆä¸€æ ·æ‰“ MOD ï¼ˆæ¨¡ç»„ï¼‰ï¼Œä¼˜é›…åœ°ä¸º CasaOS å‰ç«¯åšä¸€äº›èŠ±é‡Œèƒ¡å“¨çš„ä¿®æ”¹ã€‚ä¾‹å¦‚é¼ æ ‡ç‰¹æ•ˆã€åŠ¨æ€èƒŒæ™¯ã€ä¿®æ”¹ä¸»é¢˜ï¼Œç­‰ç­‰ã€‚
  tagline:
    en_us: MOD for CasaOS, Make your CasaOS unique
    zh_cn: ç»™ CasaOS æ‰“ MOD ï¼Œè®©ä½ çš„ CasaOS ç‹¬ä¸€æ— äºŒ
  title:
    en_us: CasaMOD
  tips:
    before_install:
      en_us: |
        1. Install CasaMOD
        2. Put the MOD directory you want to enable into the `/DATA/AppData/casamod/mod` directory.
        3. Restart CasaMOD and finish!

        You can find new MOD, and contribute your MOD [here](https://github.com/Cp0204/CasaMOD). ğŸ˜‰

        > Also, after installation you can access the icons in the `/DATA/AppData/casamod/icon` directory with `/icon/xx.png`.
      zh_cn: |
        1. å®‰è£… CasaMOD
        2. æŠŠè¦å¯ç”¨çš„MODç›®å½•æ”¾åˆ° `/DATA/AppData/casamod/mod` ç›®å½•
        3. é‡å¯ CasaMOD ï¼Œå®Œæˆï¼

        ä½ å¯ä»¥åœ¨[è¿™é‡Œ](https://github.com/Cp0204/CasaMOD/blob/main/README_CN.md)æŸ¥æ‰¾æ–°MODï¼Œå’Œè´¡çŒ®ä½ çš„MODã€‚ ğŸ˜‰

        > å¦å¤–ï¼Œå®‰è£…åä½ å¯ä»¥ç”¨ `/icon/xx.png` è®¿é—®åˆ° `/DATA/AppData/casamod/icon` ç›®å½•ä¸­çš„å›¾æ ‡ã€‚
  scheme: https
  hostname: github.com
  port_map: ''
  index: /Cp0204/CasaMOD
