name: xiaomusic
services:
  xiaomusic:
    image: docker.hanxi.cc/hanxi/xiaomusic:latest
    container_name: xiaomusic
    restart: unless-stopped
    ports:
      - "58090:8090"
    environment:
      XIAOMUSIC_PUBLIC_PORT: 58090
    volumes:
      - /DATA/AppData/xiaomusic/music:/app/music
      - /DATA/AppData/xiaomusic/conf:/app/conf
    deploy:
      resources:
        reservations:
          memory: 64M

x-casaos:
  architectures:
    - amd64
    - arm64
    - arm
  main: xiaomusic
  store_app_id: xiaomusic
  author: Cp0204
  category: Media
  description:
    en_us: Unlimited listening to songs, liberate Xiaoai speakers. Play music with Xiaoai speakers, and download music using yt-dlp.
    zh_cn: æ— é™å¬æ­Œï¼Œè§£æ”¾å°çˆ±éŸ³ç®±ã€‚ä½¿ç”¨å°çˆ±éŸ³ç®±æ’­æ”¾éŸ³ä¹ï¼ŒéŸ³ä¹ä½¿ç”¨ yt-dlp ä¸‹è½½ã€‚
  developer: hanxi
  icon: https://cdn.jsdelivr.net/gh/Cp0204/CasaOS-AppStore-Play@main/Apps/xiaomusic/icon.png
  tagline:
    en_us: Unlimited listening to songs, liberate Xiaoai speakers.
    zh_cn: æ— é™å¬æ­Œï¼Œè§£æ”¾å°çˆ±éŸ³ç®±
  tips:
    before_install:
      en_us: "If you encounter problems during the first installation, please refer to [ğŸ’¬ FAQ problem collection](https://github.com/hanxi/xiaomusic/issues/99). There are solutions to the problems encountered generally."
      zh_cn: "åˆæ¬¡å®‰è£…é‡åˆ°é—®é¢˜è¯·æŸ¥é˜… [ğŸ’¬ FAQé—®é¢˜é›†åˆ](https://github.com/hanxi/xiaomusic/issues/99) ï¼Œä¸€èˆ¬é‡åˆ°çš„é—®é¢˜éƒ½å·²ç»æœ‰è§£å†³åŠæ³•ã€‚"
  title:
    en_us: XiaoMusic
  index: /
  port_map: "58090"
