name: moviepilot
services:
    moviepilot:
        stdin_open: true
        tty: true
        container_name: moviepilot
        deploy:
          resources:
            reservations:
              memory: 256M
        network_mode: host
        volumes:
            - '/DATA/Media:/media'
            - '/DATA/AppData/$AppID/moviepilot/config:/config'
            - '/DATA/AppData/$AppID/moviepilot/core:/moviepilot/.cache/ms-playwright'
            - '/var/run/docker.sock:/var/run/docker.sock:ro'
        environment:
            - 'NGINX_PORT=3005'
            - 'PORT=3001'
            - 'AUTH_SITE=iyuu'
            - 'IYUU_SIGN=xxxx'
            - 'SUPERUSER=casaos'
            - 'API_TOKEN=moviepilot'
        restart: always
        image: jxxghp/moviepilot:1.9.9
x-casaos:
    architectures:
        - amd64
    author: CasaOS Team
    category: Media
    developer: jxxghp
    tagline:
      en_us: Video Management
      zh_cn: 视频管理
    description:
      en_us: |
        Movie Pilot is a video management tool that can automatically download and manage movies.

        Please note that this software is a bit complicated, you need to read the [documentation](https://wiki.movie-pilot.org/configuration)
      zh_cn: |
        Movie Pilot 是一个视频管理工具，可以自动下载和管理电影。

        注意本软件比较复杂，你需要阅读[文档](https://wiki.movie-pilot.org/configuration)
    title:
      en_us: Movie Pilot
      pt_br: Movie Pilot
    icon: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/MoviePilot/icon.png
    main: moviepilot
    screenshot_link:
      - https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/MoviePilot/screenshot-1.png
      - https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/MoviePilot/screenshot-2.png
    port_map: "3005"
    tips:
      before_install:
        en_us: |
          Default Account
          
          | Username | Password |
          |----------|----------|
          | `casaos`    | Get from log |
        zh_cn: |
          默认账号
          
          | 用户名 | 密码 |
          |----------|----------|
          | `casaos`    | 从日志中获取 |
